### ISSUE TITLE
I got some error could you help please

### ISSUE THREAD

**Issue by SalemAmeen** [dribnet/kerosene#2]
> > > from kerosene.datasets import svhn2
> > > Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN 5005)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/salm/anaconda2/lib/python2.7/site-packages/kerosene/datasets/svhn2.py", line 3, in <module>
> > >     from .dataset import Dataset
> > >   File "/home/salm/anaconda2/lib/python2.7/site-packages/kerosene/datasets/dataset.py", line 11, in <module>
> > >     initial_fuel_config_path = fuel.config.data_path
> > >   File "/home/salm/anaconda2/lib/python2.7/site-packages/fuel/config_parser.py", line 150, in **getattr**
> > >     "provided: {}.".format(key))
> > > fuel.exceptions.ConfigurationError: Configuration not set and no default provided: data_path.

**Comment by SalemAmeen** [comment]
I tried this command but does not work

rm -Rf ~/.kerosene/datasets

**Comment by dribnet** [comment]
Hi - I'm having kind of a crazy week but I'll be happy to look at this over the weekend. Probably the upstream fuel library might have changed and kerosene now needs a patch (I _think_ `fuel.config.data_path` could be temporarily patched to `fuel.config.data_path[0]` if you want to try a workaround)

**Comment by SalemAmeen** [comment]
Many thanks

**Comment by SalemAmeen** [comment]
Many thanks, I did the change and I received some error so any way I will wait for the update. 
BTW, this is the error I got

/home/salm/.kerosene/datasets/svhn_format_2-0.1.0.hdf5: 100% [=========================] Time: 0:05:59   5.1 MiB/s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/salm/anaconda2/lib/python2.7/site-packages/kerosene/datasets/svhn2.py", line 13, in load_data
    return SVHN2().load_data(sets, sources, fuel_dir);
  File "/home/salm/anaconda2/lib/python2.7/site-packages/kerosene/datasets/dataset.py", line 75, in load_data
    local_file = ensure_dataset_ready(self.basename, self.version, self.url_dir)
  File "/home/salm/anaconda2/lib/python2.7/site-packages/kerosene/datasets/dataset.py", line 31, in ensure_dataset_ready
    fuel.config.data_path[0] = kerosenedir
  File "/home/salm/anaconda2/lib/python2.7/site-packages/fuel/config_parser.py", line 150, in **getattr**
    "provided: {}.".format(key))
fuel.exceptions.ConfigurationError: Configuration not set and no default provided: data_path.

**Comment by mkisono** [comment]
by creating ~/.fuelrc file, I could get rid of "ConfigurationError".

```
% cat ~/.fuelrc
data_path: "/Users/myname/.keras/datasets" 
```

**Comment by SalemAmeen** [comment]
@mkisono  where can I make the file?

**Comment by pGit1** [comment]
Can someone explain concisely how to get rid of this error. I have the latest version of fuel and kerosene.

Running this:
`from kerosene.datasets import svhn2`

gets me this:

ConfigurationError                        Traceback (most recent call last)
<ipython-input-4-de0361cb4135> in <module>()
----> 1 from kerosene.datasets import svhn2

/lib/python2.7/site-packages/kerosene/datasets/svhn2.py in <module>()
      1 # -_\- coding: utf-8 -_-
      2 import fuel.datasets
----> 3 from .dataset import Dataset
      4 
      5 class SVHN2(Dataset):

/lib/python2.7/site-packages/kerosene/datasets/dataset.py in <module>()
      9 
     10 # cache this incase we load multiple datasets
---> 11 initial_fuel_config_path = fuel.config.data_path
     12 
     13 # helper class to construct local and remote filenames from metadata

/lib/python2.7/site-packages/fuel/config_parser.pyc in **getattr**(self, key)
    148         else:
    149             raise ConfigurationError("Configuration not set and no default "
--> 150                                      "provided: {}.".format(key))
    151         return config_setting['type'](value)
    152 

ConfigurationError: Configuration not set and no default provided: data_path.

**Comment by pGit1** [comment]
@mkisono where exactly do you place this code `% cat ~/.fuelrc
data_path: "/Users/myname/.keras/datasets"` to remedy the problem?

**Comment by HunterHantao** [comment]
Just create a new file gedit ~/.fuelrc 

then copy this **data_path: "/home/usrname/.keras/datasets**"  to the file works for me.
