### ISSUE TITLE
Image Labels for SVHN2 are not sequences

### ISSUE THREAD

**Issue by pGit1** [dribnet/kerosene#5]
Should the labels in SVHN2 data set not be a sequence? Right now the training labels seem to a single label for the label that is closest to the center of the image. In the SVHN1 dataset the images are definitely in a sequence. In this case can Keras support learning from a sequence of numbers?

**Comment by dribnet** [comment]
According to the SVHN authors, format2 is meant to be a MNIST-like format. The other digits are considered to be distracting digits, and the [upstream SVHN distribution](http://ufldl.stanford.edu/housenumbers/) does not include labels for them.
